yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
]

yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'{self.title}'


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.CASCADE
    )

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404

from .models import Post, Group


def index(request):
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        'posts': posts,
        'title': 'Главная страница',
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
{% load static %}

<!DOCTYPE html> 
<html lang="ru">
  <head>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
  </head>
  <body class="main_background">
    <div class="main_background_content">
      <title>
      {% block title %} {% endblock title %}
      </title>
      <header>
        {% include 'includes/header.html' %}
      </header>
      <main>
        {% block content %}
        {% endblock %}
      </main>
    </div>
    <footer class="footer_background">
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<div>
</div>

yatube/templates/includes/header.html
{% load static %}
<div class="header row justify-content-center">
    <div class="header_logo flex">
        <a href="{% url "posts:index" %}">
            <img class="header_logo_img" src="{% static 'img/coffee_cookies1.png' %}">
        </a>
        <h1 class="header_logo_text">Коффенье</h1>
    </div>
</div>
<style>* color: "red" </style>

yatube/templates/posts/group_list.html
{% extends 'base.html'%}
{% block content %}

<div class="main_content"> 
  <div class="main_content_pading">
    <h1>{{ group.title }}</h1>
    <p>
      {{ group.description }}
    </p>
    {% for post in posts %}
      <article>
        <p>
          Автор: {{ post.author.get_full_name }}
        </p>
        <p>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}    
        </p>
        <p>
          {{ post.text }}
        </p>         
      </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html'%}
{% block content %}

<div> 
  <h1 class="text-center"> 
    {{ title }}
  </h1>
  <div class="text-center">
    <a href="{% url 'posts:group_list' 'coffe' %}">
      Перейти в группу
    </a>
  </div>
  <div class="pb-5 pt-5 post_list_text">
    {% for post in posts %}
    <p class="post_list_author">
      Автор: {{ post.author.get_full_name }}
    </p> 
    <p class="post_list_author">
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </p>
      <p>{{ post.text }}</p>    
      {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %} 
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
</div>
{% endblock %}